-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Profiles (Extends Supabase Auth)
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  email text not null,
  full_name text,
  phone text,
  role text default 'customer' check (role in ('admin', 'customer', 'staff')),
  avatar_url text,
  loyalty_points integer default 0,
  referral_code text unique,
  referred_by_user_id uuid references profiles(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 2. Categories
create table if not exists categories (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  slug text not null unique,
  description text,
  parent_id uuid references categories(id) on delete set null,
  image_url text,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 3. Products
create table if not exists products (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  slug text not null unique,
  description text,
  sku text unique,
  base_price numeric(10, 2) not null,
  discount_price numeric(10, 2),
  stock integer default 0,
  status text default 'draft' check (status in ('draft', 'published', 'archived')),
  category_id uuid references categories(id) on delete set null,
  tags text[],
  thumbnail_url text,
  gallery_urls text[],
  is_new boolean default false,
  is_featured boolean default false,
  brand text,
  sizes text[],
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 4. Product Variants
create table if not exists product_variants (
  id uuid default gen_random_uuid() primary key,
  product_id uuid references products(id) on delete cascade not null,
  name text not null, -- e.g., "Size", "Color"
  value text not null, -- e.g., "M", "Red"
  price_adjustment numeric(10, 2) default 0,
  stock integer default 0,
  sku text,
  created_at timestamptz default now()
);

-- 5. Carts
create table if not exists carts (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) on delete cascade, -- Nullable for guest carts if needed
  session_id text, -- For guest carts
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 6. Cart Items
create table if not exists cart_items (
  id uuid default gen_random_uuid() primary key,
  cart_id uuid references carts(id) on delete cascade not null,
  product_id uuid references products(id) on delete cascade not null,
  variant_id uuid references product_variants(id),
  quantity integer default 1 check (quantity > 0),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 7. Shipping Addresses
create table if not exists shipping_addresses (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  address_line1 text not null,
  address_line2 text,
  city text not null,
  state text,
  postal_code text not null,
  country text not null default 'Bangladesh',
  phone text,
  is_default boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 8. Coupons
create table if not exists coupons (
  id uuid default gen_random_uuid() primary key,
  code text not null unique,
  type text default 'percentage' check (type in ('percentage', 'fixed_amount')),
  value numeric(10, 2) not null,
  min_order_amount numeric(10, 2) default 0,
  start_date timestamptz default now(),
  end_date timestamptz,
  usage_limit integer,
  per_user_limit integer default 1,
  product_ids uuid[], -- Array of product IDs this coupon is valid for
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 9. Orders
-- Note: changed id to text to support custom IDs like 'SV12345678' generated by frontend
create table if not exists orders (
  id text primary key,
  user_id uuid references profiles(id) on delete set null,
  shipping_address_id uuid references shipping_addresses(id),
  shipping_address_snapshot jsonb, -- Store full address at time of order
  status text default 'pending' check (status in ('pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded')),
  total_amount numeric(10, 2) not null,
  discount_amount numeric(10, 2) default 0,
  shipping_cost numeric(10, 2) default 0,
  final_amount numeric(10, 2) not null,
  payment_method text, -- e.g., 'bkash', 'cod', 'stripe'
  payment_status text default 'pending' check (payment_status in ('pending', 'paid', 'failed')),
  coupon_code text,
  tracking_number text,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 10. Order Items
create table if not exists order_items (
  id uuid default gen_random_uuid() primary key,
  order_id text references orders(id) on delete cascade not null,
  product_id uuid references products(id) on delete set null,
  variant_id uuid references product_variants(id),
  product_name text not null, -- Snapshot
  quantity integer not null,
  price numeric(10, 2) not null, -- Snapshot of price at purchase
  created_at timestamptz default now()
);

-- 11. Payments
create table if not exists payments (
  id uuid default gen_random_uuid() primary key,
  order_id text references orders(id) on delete cascade not null,
  transaction_id text,
  provider text, -- e.g., 'stripe', 'sslcommerz'
  amount numeric(10, 2) not null,
  currency text default 'BDT',
  status text default 'pending',
  created_at timestamptz default now()
);

-- 12. Wishlists
create table if not exists wishlists (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  product_id uuid references products(id) on delete cascade not null,
  created_at timestamptz default now(),
  unique(user_id, product_id)
);

-- 13. Reviews
create table if not exists reviews (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  product_id uuid references products(id) on delete cascade not null,
  rating integer check (rating >= 1 and rating <= 5),
  comment text,
  is_approved boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 14. Banners
create table if not exists banners (
  id uuid default gen_random_uuid() primary key,
  title text,
  image_url text not null,
  link_url text,
  position integer default 0,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 15. Site Settings
create table if not exists site_settings (
  id uuid default gen_random_uuid() primary key,
  key text unique not null,
  value jsonb not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 16. Admin Logs
create table if not exists admin_logs (
  id uuid default gen_random_uuid() primary key,
  admin_id uuid references profiles(id) on delete set null,
  action text not null,
  details jsonb,
  ip_address text,
  created_at timestamptz default now()
);

-- 17. Loyalty Transactions
create table if not exists loyalty_transactions (
    id uuid default gen_random_uuid() primary key,
    user_id uuid references profiles(id) on delete cascade not null,
    type text not null, -- 'EARN_PURCHASE', 'EARN_REFERRAL', 'WITHDRAW_REQUEST', 'WITHDRAW_REJECTED_REFUND', 'WITHDRAW_COMPLETED'
    points integer not null,
    tk_amount numeric(10, 2) default 0,
    order_id text, -- Can be internal ID or string ID
    meta_json jsonb,
    created_at timestamptz default now()
);

-- 18. Withdraw Requests
create table if not exists withdraw_requests (
    id uuid default gen_random_uuid() primary key,
    user_id uuid references profiles(id) on delete cascade not null,
    points_amount integer not null,
    withdraw_tk numeric(10, 2) not null,
    method text not null, -- 'BKASH', 'NAGAD'
    number text not null,
    status text default 'PROCESSING' check (status in ('PROCESSING', 'COMPLETED', 'REJECTED')),
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- RLS Policies

-- Helper Function: is_admin (SECURITY DEFINER to avoid RLS recursion)
CREATE OR REPLACE FUNCTION public.is_admin() 
RETURNS boolean 
LANGUAGE plpgsql 
SECURITY DEFINER 
SET search_path = public
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 
    FROM profiles 
    WHERE id = auth.uid() 
    AND role = 'admin'
  );
END;
$$;

-- Enable RLS on all tables
alter table profiles enable row level security;
alter table categories enable row level security;
alter table products enable row level security;
alter table product_variants enable row level security;
alter table carts enable row level security;
alter table cart_items enable row level security;
alter table shipping_addresses enable row level security;
alter table coupons enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
alter table payments enable row level security;
alter table wishlists enable row level security;
alter table reviews enable row level security;
alter table banners enable row level security;
alter table site_settings enable row level security;
alter table admin_logs enable row level security;
alter table loyalty_transactions enable row level security;
alter table withdraw_requests enable row level security;

-- Helper block for policies
-- Profiles
-- Helper block for policies
-- Profiles
do $$ begin
  -- 1. Read: Public (avoids recursion)
  if not exists (select from pg_policies where policyname = 'Public profiles are viewable by everyone' and tablename = 'profiles') then
    create policy "Public profiles are viewable by everyone" on profiles for select using (true);
  end if;
  
  -- 2. Insert: Self
  if not exists (select from pg_policies where policyname = 'Users can insert their own profile' and tablename = 'profiles') then
    create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);
  end if;
  
  -- 3. Update: Self
  if not exists (select from pg_policies where policyname = 'Users can update own profile' and tablename = 'profiles') then
    create policy "Users can update own profile" on profiles for update using (auth.uid() = id);
  end if;
  
  -- 4. Update: Admin (using is_admin)
  if not exists (select from pg_policies where policyname = 'Admins can update any profile' and tablename = 'profiles') then
    create policy "Admins can update any profile" on profiles for update using (is_admin());
  end if;
  
  -- 5. Delete: Admin (using is_admin)
  if not exists (select from pg_policies where policyname = 'Admins can delete any profile' and tablename = 'profiles') then
    create policy "Admins can delete any profile" on profiles for delete using (is_admin());
  end if;
end $$;

-- Categories (Viewable by everyone, Admin manage)
do $$ begin
  if not exists (select from pg_policies where policyname = 'Categories are viewable by everyone' and tablename = 'categories') then
    create policy "Categories are viewable by everyone" on categories for select using (true);
  end if;
  if not exists (select from pg_policies where policyname = 'Admins can maintain categories' and tablename = 'categories') then
    create policy "Admins can maintain categories" on categories for all using (
      is_admin()
    );
  end if;
end $$;

-- Products
do $$ begin
  if not exists (select from pg_policies where policyname = 'Published products are viewable by everyone' and tablename = 'products') then
    create policy "Published products are viewable by everyone" on products for select using (status = 'published');
  end if;
  -- Add admin policy again to be sure
  if not exists (select from pg_policies where policyname = 'Admins can maintain products' and tablename = 'products') then
    create policy "Admins can maintain products" on products for all using (
      is_admin()
    );
  end if;
end $$;

-- Product Variants (Viewable by everyone, Admin manage)
do $$ begin
  if not exists (select from pg_policies where policyname = 'Product variants are viewable by everyone' and tablename = 'product_variants') then
    create policy "Product variants are viewable by everyone" on product_variants for select using (true);
  end if;
  if not exists (select from pg_policies where policyname = 'Admins can maintain product variants' and tablename = 'product_variants') then
    create policy "Admins can maintain product variants" on product_variants for all using (
      is_admin()
    );
  end if;
end $$;

-- Carts
do $$ begin
  if not exists (select from pg_policies where policyname = 'Users can view own cart' and tablename = 'carts') then
    create policy "Users can view own cart" on carts for select using (user_id = auth.uid());
  end if;
  if not exists (select from pg_policies where policyname = 'Users can insert own cart' and tablename = 'carts') then
    create policy "Users can insert own cart" on carts for insert with check (user_id = auth.uid());
  end if;
  if not exists (select from pg_policies where policyname = 'Users can update own cart' and tablename = 'carts') then
    create policy "Users can update own cart" on carts for update using (user_id = auth.uid());
  end if;
  if not exists (select from pg_policies where policyname = 'Admins can view all carts' and tablename = 'carts') then
    create policy "Admins can view all carts" on carts for select using (is_admin());
  end if;
end $$;

-- Cart Items (Users can see/manage their own, Admins can see all)
do $$ begin
  if not exists (select from pg_policies where policyname = 'Users can view own cart items' and tablename = 'cart_items') then
    create policy "Users can view own cart items" on cart_items for select using (cart_id in (select id from carts where user_id = auth.uid()));
  end if;
  if not exists (select from pg_policies where policyname = 'Users can insert own cart items' and tablename = 'cart_items') then
    create policy "Users can insert own cart items" on cart_items for insert with check (cart_id in (select id from carts where user_id = auth.uid()));
  end if;
  if not exists (select from pg_policies where policyname = 'Users can update own cart items' and tablename = 'cart_items') then
    create policy "Users can update own cart items" on cart_items for update using (cart_id in (select id from carts where user_id = auth.uid()));
  end if;
  if not exists (select from pg_policies where policyname = 'Users can delete own cart items' and tablename = 'cart_items') then
    create policy "Users can delete own cart items" on cart_items for delete using (cart_id in (select id from carts where user_id = auth.uid()));
  end if;
  if not exists (select from pg_policies where policyname = 'Admins can manage all cart items' and tablename = 'cart_items') then
    create policy "Admins can manage all cart items" on cart_items for all using (is_admin());
  end if;
end $$;

-- Shipping Addresses (Users can see/manage their own, Admins can see all)
do $$ begin
  if not exists (select from pg_policies where policyname = 'Users can view own shipping addresses' and tablename = 'shipping_addresses') then
    create policy "Users can view own shipping addresses" on shipping_addresses for select using (user_id = auth.uid());
  end if;
  if not exists (select from pg_policies where policyname = 'Users can insert own shipping addresses' and tablename = 'shipping_addresses') then
    create policy "Users can insert own shipping addresses" on shipping_addresses for insert with check (user_id = auth.uid());
  end if;
  if not exists (select from pg_policies where policyname = 'Users can update own shipping addresses' and tablename = 'shipping_addresses') then
    create policy "Users can update own shipping addresses" on shipping_addresses for update using (user_id = auth.uid());
  end if;
  if not exists (select from pg_policies where policyname = 'Users can delete own shipping addresses' and tablename = 'shipping_addresses') then
    create policy "Users can delete own shipping addresses" on shipping_addresses for delete using (user_id = auth.uid());
  end if;
  if not exists (select from pg_policies where policyname = 'Admins can manage all shipping addresses' and tablename = 'shipping_addresses') then
    create policy "Admins can manage all shipping addresses" on shipping_addresses for all using (is_admin());
  end if;
end $$;

-- Coupons (Public view if active, Admin manage)
do $$ begin
  if not exists (select from pg_policies where policyname = 'Active coupons are viewable by everyone' and tablename = 'coupons') then
    create policy "Active coupons are viewable by everyone" on coupons for select using (is_active = true AND (end_date IS NULL OR end_date > now()));
  end if;
  if not exists (select from pg_policies where policyname = 'Admins can maintain coupons' and tablename = 'coupons') then
    create policy "Admins can maintain coupons" on coupons for all using (
      is_admin()
    );
  end if;
end $$;

-- Orders
do $$ begin
  if not exists (select from pg_policies where policyname = 'Users can view own orders' and tablename = 'orders') then
    create policy "Users can view own orders" on orders for select using (user_id = auth.uid());
  end if;
  if not exists (select from pg_policies where policyname = 'Users can insert own orders' and tablename = 'orders') then
    create policy "Users can insert own orders" on orders for insert with check (user_id = auth.uid());
  end if;
  if not exists (select from pg_policies where policyname = 'Admins can view all orders' and tablename = 'orders') then
    create policy "Admins can view all orders" on orders for select using (
      is_admin()
    );
  end if;
  if not exists (select from pg_policies where policyname = 'Admins can update all orders' and tablename = 'orders') then
    create policy "Admins can update all orders" on orders for update using (is_admin());
  end if;
end $$;

-- Order Items (Users can view their own order items, Admins can view all)
do $$ begin
  if not exists (select from pg_policies where policyname = 'Users can view own order items' and tablename = 'order_items') then
    create policy "Users can view own order items" on order_items for select using (order_id in (select id from orders where user_id = auth.uid()));
  end if;
  if not exists (select from pg_policies where policyname = 'Admins can view all order items' and tablename = 'order_items') then
    create policy "Admins can view all order items" on order_items for select using (is_admin());
  end if;
  if not exists (select from pg_policies where policyname = 'Admins can insert order items' and tablename = 'order_items') then
    create policy "Admins can insert order items" on order_items for insert with check (is_admin());
  end if;
end $$;

-- Payments (Users can view their own payments, Admins can view all)
do $$ begin
  if not exists (select from pg_policies where policyname = 'Users can view own payments' and tablename = 'payments') then
    create policy "Users can view own payments" on payments for select using (order_id in (select id from orders where user_id = auth.uid()));
  end if;
  if not exists (select from pg_policies where policyname = 'Admins can view all payments' and tablename = 'payments') then
    create policy "Admins can view all payments" on payments for select using (is_admin());
  end if;
  if not exists (select from pg_policies where policyname = 'Admins can insert payments' and tablename = 'payments') then
    create policy "Admins can insert payments" on payments for insert with check (is_admin());
  end if;
end $$;

-- Wishlists (Users can manage their own)
do $$ begin
  if not exists (select from pg_policies where policyname = 'Users can view own wishlists' and tablename = 'wishlists') then
    create policy "Users can view own wishlists" on wishlists for select using (user_id = auth.uid());
  end if;
  if not exists (select from pg_policies where policyname = 'Users can insert own wishlists' and tablename = 'wishlists') then
    create policy "Users can insert own wishlists" on wishlists for insert with check (user_id = auth.uid());
  end if;
  if not exists (select from pg_policies where policyname = 'Users can delete own wishlists' and tablename = 'wishlists') then
    create policy "Users can delete own wishlists" on wishlists for delete using (user_id = auth.uid());
  end if;
end $$;

-- Reviews (Public view, Users can manage their own, Admins can manage all)
do $$ begin
  if not exists (select from pg_policies where policyname = 'Approved reviews are viewable by everyone' and tablename = 'reviews') then
    create policy "Approved reviews are viewable by everyone" on reviews for select using (is_approved = true);
  end if;
  if not exists (select from pg_policies where policyname = 'Users can insert own reviews' and tablename = 'reviews') then
    create policy "Users can insert own reviews" on reviews for insert with check (user_id = auth.uid());
  end if;
  if not exists (select from pg_policies where policyname = 'Users can update own reviews' and tablename = 'reviews') then
    create policy "Users can update own reviews" on reviews for update using (user_id = auth.uid());
  end if;
  if not exists (select from pg_policies where policyname = 'Admins can manage all reviews' and tablename = 'reviews') then
    create policy "Admins can manage all reviews" on reviews for all using (is_admin());
  end if;
end $$;

-- Banners (Public view, Admin manage)
do $$ begin
  if not exists (select from pg_policies where policyname = 'Banners are viewable by everyone' and tablename = 'banners') then
    create policy "Banners are viewable by everyone" on banners for select using (is_active = true);
  end if;
  if not exists (select from pg_policies where policyname = 'Admins can maintain banners' and tablename = 'banners') then
    create policy "Admins can maintain banners" on banners for all using (
      is_admin()
    );
  end if;
end $$;

-- Site Settings (Admins can manage, Public can view specific keys)
do $$ begin
  if not exists (select from pg_policies where policyname = 'Admins can manage site settings' and tablename = 'site_settings') then
    create policy "Admins can manage site settings" on site_settings for all using (
      is_admin()
    );
  end if;
  
  if not exists (select from pg_policies where policyname = 'Public can view store settings' and tablename = 'site_settings') then
    create policy "Public can view store settings" on site_settings for select using (
      key in ('settings_store', 'settings_banners')
    );
  end if;
end $$;

-- Admin Logs (Admins can view)
do $$ begin
  if not exists (select from pg_policies where policyname = 'Admins can view admin logs' and tablename = 'admin_logs') then
    create policy "Admins can view admin logs" on admin_logs for select using (
      is_admin()
    );
  end if;
end $$;

-- Loyalty Transactions
do $$ begin
  if not exists (select from pg_policies where policyname = 'Users can view own transactions' and tablename = 'loyalty_transactions') then
    create policy "Users can view own transactions" on loyalty_transactions for select using (user_id = auth.uid());
  end if;
  if not exists (select from pg_policies where policyname = 'Users can insert system transactions' and tablename = 'loyalty_transactions') then
    create policy "Users can insert system transactions" on loyalty_transactions for insert with check (user_id = auth.uid());
  end if;
  if not exists (select from pg_policies where policyname = 'Admins can view all transactions' and tablename = 'loyalty_transactions') then
    create policy "Admins can view all transactions" on loyalty_transactions for select using (
        is_admin()
    );
  end if;
  if not exists (select from pg_policies where policyname = 'Admins can insert loyalty transactions' and tablename = 'loyalty_transactions') then
    create policy "Admins can insert loyalty transactions" on loyalty_transactions for insert with check (is_admin());
  end if;
end $$;

-- Withdraw Requests
do $$ begin
  if not exists (select from pg_policies where policyname = 'Users can view own withdraw requests' and tablename = 'withdraw_requests') then
    create policy "Users can view own withdraw requests" on withdraw_requests for select using (user_id = auth.uid());
  end if;
  if not exists (select from pg_policies where policyname = 'Users can insert own withdraw requests' and tablename = 'withdraw_requests') then
    create policy "Users can insert own withdraw requests" on withdraw_requests for insert with check (user_id = auth.uid());
  end if;
  if not exists (select from pg_policies where policyname = 'Admins can maintain withdraw requests' and tablename = 'withdraw_requests') then
    create policy "Admins can maintain withdraw requests" on withdraw_requests for all using (
        is_admin()
    );
  end if;
end $$;

-- Triggers for updated_at
create or replace function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

-- Helper to safely create triggers if they don't exist
do $$ begin
  if not exists (select 1 from pg_trigger where tgname = 'update_profiles_updated_at') then
    create trigger update_profiles_updated_at before update on profiles for each row execute function update_updated_at_column();
  end if;
  
  if not exists (select 1 from pg_trigger where tgname = 'update_categories_updated_at') then
    create trigger update_categories_updated_at before update on categories for each row execute function update_updated_at_column();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'update_products_updated_at') then
    create trigger update_products_updated_at before update on products for each row execute function update_updated_at_column();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'update_carts_updated_at') then
    create trigger update_carts_updated_at before update on carts for each row execute function update_updated_at_column();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'update_cart_items_updated_at') then
    create trigger update_cart_items_updated_at before update on cart_items for each row execute function update_updated_at_column();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'update_shipping_addresses_updated_at') then
    create trigger update_shipping_addresses_updated_at before update on shipping_addresses for each row execute function update_updated_at_column();
  end if;
  
  if not exists (select 1 from pg_trigger where tgname = 'update_coupons_updated_at') then
    create trigger update_coupons_updated_at before update on coupons for each row execute function update_updated_at_column();
  end if;
  
  if not exists (select 1 from pg_trigger where tgname = 'update_orders_updated_at') then
    create trigger update_orders_updated_at before update on orders for each row execute function update_updated_at_column();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'update_reviews_updated_at') then
    create trigger update_reviews_updated_at before update on reviews for each row execute function update_updated_at_column();
  end if;
  
  if not exists (select 1 from pg_trigger where tgname = 'update_banners_updated_at') then
    create trigger update_banners_updated_at before update on banners for each row execute function update_updated_at_column();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'update_site_settings_updated_at') then
    create trigger update_site_settings_updated_at before update on site_settings for each row execute function update_updated_at_column();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'update_withdraw_requests_updated_at') then
    create trigger update_withdraw_requests_updated_at before update on withdraw_requests for each row execute function update_updated_at_column();
  end if;
end $$;

-- Handle New User (Sync Profile with Auth)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.profiles (id, full_name, avatar_url, email)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url',
    new.email
  );
  return new;
end;
$$;

-- Trigger for new user
do $$ begin
  if not exists (select 1 from pg_trigger where tgname = 'on_auth_user_created') then
    create trigger on_auth_user_created
      after insert on auth.users
      for each row execute procedure public.handle_new_user();
  end if;
end $$;